"""Add embedding to KGNode

Revision ID: 3e00aee59da0
Revises: 9f3864f434ce
Create Date: 2026-05-16 22:50:05.918168

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3e00aee59da0'
down_revision: Union[str, Sequence[str], None] = '9f3864f434ce'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('kg_nodes', sa.Column('embedding', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('kg_nodes', 'embedding')
    # ### end Alembic commands ###
